# Environment configuration for HSP_DAQ compatible with Windows and macOS
name: HSP_DAQ
channels:
  - conda-forge
  - defaults
  - pyg
dependencies:
  # Core Python and utilities
  - python=3.12
  - pip>=24.0
  - setuptools>=78.0
  - wheel>=0.45
  - python_abi=3.12

  # Compression and data handling
  - bzip2>=1.0.8
  - xz>=5.8
  - zlib>=1.3
  - zstd>=1.5
  - lerc>=4.0

  # Certificates and networking
  - ca-certificates>=2024.0
  - openssl>=3.3

  # Database and file handling
  - sqlite>=3.45
  - libpng>=1.6
  - libjpeg-turbo>=3.0
  - libtiff>=4.6
  - libwebp-base>=1.4
  - libxml2>=2.12
  - libxslt>=1.1

  # Fonts and rendering
  - freetype>=2.12
  - fontconfig>=2.14
  - font-ttf-dejavu-sans-mono>=2.37
  - font-ttf-inconsolata>=3.000
  - font-ttf-source-code-pro>=2.038
  - font-ttf-ubuntu>=0.83
  - fonts-conda-ecosystem>=1
  - fonts-conda-forge>=1

  # Numerical and scientific computing
  - numpy>=2.0
  - pandas>=2.2
  - scipy>=1.14
  - scikit-learn>=1.5
  - libblas>=3.9
  - libcblas>=3.9
  - liblapack>=3.9
  - libopenblas>=0.3
  - joblib>=1.5
  - threadpoolctl>=3.5

  # GUI and visualization
  - pyside6>=6.7
  - qt6-main>=6.7
  - cairo>=1.18
  - harfbuzz>=9.0
  - pixman>=0.43

  # Time and date handling
  - python-dateutil>=2.9 
  - pytz>=2025.1
  - tzdata>=2025 # [unix]
  - python-tzdata>=2025 # [unix]

  # Additional utilities
  - libffi>=3.4
  - ncurses>=6.4 # [unix]
  - readline>=8.2 # [unix]
  - tk>=8.6
  - expat>=2.6
  - pcre2>=10.43

  # Pip-installed packages
  - pip:
      - aiohappyeyeballs>=2.4
      - aiohttp>=3.10
      - aiosignal>=1.3
      - attrs>=25.2
      - blinker>=1.8
      - cachetools>=5.5
      - certifi>=2024.8
      - charset-normalizer>=3.4
      - click>=8.1
      - dash>=3.0
      - digi-xbee>=1.5
      - durationpy>=0.9
      - flask>=3.0
      - frozenlist>=1.4
      - google-auth>=2.34
      - idna>=3.8
      - importlib-metadata>=8.5
      - inflection>=0.5
      - iso8601>=2.1
      - itsdangerous>=2.2
      - jinja2>=3.1
      - kopf>=1.37
      - kubernetes>=30.0
      - labjack-ljm>=1.23
      - markupsafe>=3.0
      - multidict>=6.1
      - narwhals>=1.36
      - nest-asyncio>=1.6
      - oauthlib>=3.2
      - packaging>=24.1
      - paho-mqtt>=2.1
      - plotly>=6.0
      - propcache>=0.3
      - pyasn1>=0.6
      - pyasn1-modules>=0.4
      - pyserial>=3.5
      - pysimplegui>=5.0
      - python-box>=7.2
      - python-json-logger>=3.3
      - pyyaml>=6.0
      - pyzed>=1.3
      - requests>=2.32
      - requests-oauthlib>=2.0
      - retrying>=1.3
      - rsa>=4.9
      - typing-extensions>=4.12
      - urllib3>=2.2
      - websocket-client>=1.8
      - werkzeug>=3.0
      - yarl>=1.14
      - zipp>=3.20
# Note: Prefix is omitted to allow Conda to use the default environment location